/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ed_recurso_8210126;

import org.junit.jupiter.api.Test;

import ed_recurso_8210126.App.App;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
